// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqIiEK8I4GNechlVhQIgcbOW81-7tQ5y8',
    appId: '1:795451800994:web:e4e52dd121c6bcd75b86fb',
    messagingSenderId: '795451800994',
    projectId: 'chattingapp-740f1',
    authDomain: 'chattingapp-740f1.firebaseapp.com',
    storageBucket: 'chattingapp-740f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQruwCvH41JY4MLY7R9xGv1zL_vZKYves',
    appId: '1:795451800994:android:5b14942ee59729295b86fb',
    messagingSenderId: '795451800994',
    projectId: 'chattingapp-740f1',
    storageBucket: 'chattingapp-740f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfABUALjBKMGHghvyKSCy3S1aGOhs8JI',
    appId: '1:795451800994:ios:637548c4d81bdf2c5b86fb',
    messagingSenderId: '795451800994',
    projectId: 'chattingapp-740f1',
    storageBucket: 'chattingapp-740f1.firebasestorage.app',
    iosBundleId: 'com.example.hiConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqfABUALjBKMGHghvyKSCy3S1aGOhs8JI',
    appId: '1:795451800994:ios:637548c4d81bdf2c5b86fb',
    messagingSenderId: '795451800994',
    projectId: 'chattingapp-740f1',
    storageBucket: 'chattingapp-740f1.firebasestorage.app',
    iosBundleId: 'com.example.hiConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqIiEK8I4GNechlVhQIgcbOW81-7tQ5y8',
    appId: '1:795451800994:web:40fa4e59112843075b86fb',
    messagingSenderId: '795451800994',
    projectId: 'chattingapp-740f1',
    authDomain: 'chattingapp-740f1.firebaseapp.com',
    storageBucket: 'chattingapp-740f1.firebasestorage.app',
  );
}
